// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBocywsV08XSs0K9xDyd0Aw9kP1Phrcxwc',
    appId: '1:110142124750:web:10c39668c8d9fbb594d69f',
    messagingSenderId: '110142124750',
    projectId: 'todoapp-5a4bf',
    authDomain: 'todoapp-5a4bf.firebaseapp.com',
    storageBucket: 'todoapp-5a4bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAjlhe-DegP7XKuiZR12F6eMJtdJRbkus',
    appId: '1:110142124750:android:51ae8204b7c9f4da94d69f',
    messagingSenderId: '110142124750',
    projectId: 'todoapp-5a4bf',
    storageBucket: 'todoapp-5a4bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhBPdtpTTgIHEQ3A-PHXkfLn0w1m0fsA8',
    appId: '1:110142124750:ios:6f2bfccd6a9ba26b94d69f',
    messagingSenderId: '110142124750',
    projectId: 'todoapp-5a4bf',
    storageBucket: 'todoapp-5a4bf.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhBPdtpTTgIHEQ3A-PHXkfLn0w1m0fsA8',
    appId: '1:110142124750:ios:6f2bfccd6a9ba26b94d69f',
    messagingSenderId: '110142124750',
    projectId: 'todoapp-5a4bf',
    storageBucket: 'todoapp-5a4bf.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBocywsV08XSs0K9xDyd0Aw9kP1Phrcxwc',
    appId: '1:110142124750:web:e71118f2fe49071194d69f',
    messagingSenderId: '110142124750',
    projectId: 'todoapp-5a4bf',
    authDomain: 'todoapp-5a4bf.firebaseapp.com',
    storageBucket: 'todoapp-5a4bf.appspot.com',
  );
}
